[project]
name = "tpk"
authors = [{ name = "Rudolf Kolbe", email = "rkolbe96@tuta.io" }]
description = "A package for parsing type tree packages (TPK)"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "lz4",
    "brotli",
    "typing_extensions",
]
dynamic = ["version"]

[project.scripts]
tpk_helper = "tpk.cli:main"

[project.optional-dependencies]
# optional dependencies must be lowercase/normalized
tests = ["pytest"]
dev = ["ruff", "tpk[tests]"]

[project.urls]
"Homepage" = "https://github.com/K0lb3/tpk"
"Bug Tracker" = "https://github.com/K0lb3/tpk/issues"

[tool.setuptools.dynamic]
version = { attr = "tpk.__version__" }

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
pythonVersion = "3.8"
