target-version = "py38"
include = [
    "tpk_ar/*.py",
    "tests/*.py",
]
line-length = 120

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # isort
    "I",
]

[lint.pydocstyle]
# Enforce numpy-style docstrings
convention = "numpy"

[lint.per-file-ignores]
# Ignore docstring requirements for test files
"tpk_ar/__init__.py" = ["F401"]
"tests/**/*.py" = ["D"]
